
project_id = "extdyjkfgftbokabiamc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = false

[functions.stripe-start-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-booking-confirmation-emails]
verify_jwt = false
