
project_id = "extdyjkfgftbokabiamc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://7e830e49-c9ab-402a-82b9-2f0f8fa7d484.sandbox.lovable.dev"
additional_redirect_urls = ["https://preview--vip-passenger.lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = false

[functions.stripe-start-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-payment-status]
verify_jwt = true

[functions.send-booking-confirmation-emails]
verify_jwt = false
