import React, { useState, useEffect } from 'react';
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { MapPin, Clock, Phone, User, MessageCircle, Bell, BellOff, Settings, Star, DollarSign, Calendar, TrendingUp } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { format, subDays, startOfWeek, endOfWeek, parseISO } from 'date-fns';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { StatusBadges } from "@/components/status/StatusBadges";
import { RideStatusModal } from '@/components/RideStatusModal';
import { UniversalRideCard } from '@/components/dashboard/UniversalRideCard';
import { OrganizedBookingsList } from '@/components/dashboard/OrganizedBookingsList';
import { MessagesTab } from '@/components/dashboard/MessagesTab';
import { PaymentsTab } from '@/components/PaymentsTab';
import { EarningsSection } from '@/components/dashboard/EarningsSection';
import { BottomNavigation } from '@/components/dashboard/BottomNavigation';
import { FloatingActionButton } from '@/components/dashboard/FloatingActionButton';
import { ProfileHeader } from '@/components/dashboard/ProfileHeader';
import { NotificationManager } from '@/components/NotificationManager';
import { useRealtimeBookings } from '@/hooks/useRealtimeBookings';
