// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://extdyjkfgftbokabiamc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4dGR5amtmZ2Z0Ym9rYWJpYW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTU2MjMsImV4cCI6MjA2ODc5MTYyM30.BQsUy0nX3Aj_aAzTSGGQFWWt7zFYf7fQmKPveRsM3vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});